### ISSUE TITLE
Remove react-native-elements

### ISSUE THREAD

**Issue by criszz77** [plaut-ro/luna#14]
**Is your feature request related to a problem? Please describe.**
Luna is being described as a boilerplate with minimal configuration. However, react-native-elements is not necessary and can be removed.

**Describe the solution you'd like**
Remove react-native-elements

**Comment by mikehardy** [comment]
react-native-paper is a similar library and I was contemplating using it personally so for what it's worth I agree with this - there are multiple choices so it should be left to the user. I still like vector-icons and navigation integrated though as I think there is only one choice that works on web for each of those areas, and they are both lively / well-maintained projects that the community has basically "voted" for with usage

**Comment by criszz77** [comment]
Indeed, I agree with you. react-native-vector-icons and react-navigations are recommended for usage on the web according to React Native Directory (https://reactnative.directory/?order=stars&web=true&android=true&ios=true&isRecommended=true) and I also think that they should stay.
