### ISSUE TITLE
Unmaintained packages.

### ISSUE THREAD

**Issue by criszz77** [plaut-ro/luna#21]
**Is your feature request related to a problem? Please describe.**
Currently, Luna is using [react-app-rewired](https://github.com/timarney/react-app-rewired) and [customize-cra](https://github.com/arackaf/customize-cra) to configure webpack without ejecting, however those libraries seem unmaintained.

**Describe the solution you'd like**
Use [CRACO](https://github.com/gsoft-inc/craco) instead.

**Comment by mikehardy** [comment]
Oh wow, I have very little experience on the web side, so seeing the landscape of boilerplate and override projects in that ecosystem is really interesting. Moving to CRACO does seem like a good path forward

**Comment by criszz77** [comment]
Indeed, CRACO is also new for me so I'll have to try it out, I was more familiar with react-app-rewired.
