### ISSUE TITLE
CI should publish web app to github pages

### ISSUE THREAD

**Issue by mikehardy** [plaut-ro/luna#37]
I keep remembering and forgetting this, and it is something I want to do for the react-native-firebase-authentication-example as well - but I should make (or anyone could :-), but I'll do it eventually) a .github/workflow that publishes the template to github pages so people may use it live

**Comment by mikehardy** [comment]
Looks pretty easy actually, will require some involvement from repo owner after first attempt (which should fail) then second attempt will go

https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-first-deployment-with-github_token

**Comment by mikehardy** [comment]
initial research done, no time to implement at the moment, but now there's a roadmap for my future self (or anyone) to just crank it out :)

**Comment by criszz77** [comment]
🚀 This actually is a great idea! Niiiice
